name: Build & upload to Firebase App Distribution 

on:
  pull_request:
    branches: [ android-main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Access GH_CLIENT_ID
      env:    
        GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      run: echo "GH_CLIENT_ID=\"$GH_CLIENT_ID\"" > android/2023-emmsale/local.properties
    
    - name: Access GOOGLE_SERVICE
      env:    
         GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
      run: echo '${{ secrets.GOOGLE_SERVICE }}' > android/2023-emmsale/app/google-services.json
      
    - name: build release 
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale assembleDebug
      
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: kerdy-team
        file: android/2023-emmsale/app/build/outputs/apk/debug/app-debug.apk
        
    - name: 슬랙에 apk 업로드 브로드캐스트
      uses: 8398a7/action-slack@v3
      with:
        mention: 'here'
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        file_path: 'android/2023-emmsale/app/build/outputs/apk/debug/app-debug.apk'
        file_type: 'apk'
        initial_comment: '테스트 어플리케이션이 출시되었어요! QA 진행을 부탁드립니다 : )'
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_SLACK_WEBHOOK_URL }}
      if: always()
