name: Kerdy Android CI

on:
  push:
    branches: [ "android-main" ]
  pull_request:
    branches: [ "android-main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Change wrapper permissions 
      run: chmod +x ./android/2023-emmsale/gradlew
    
    - name: Access GH_CLIENT_ID
      env:    
        GH_CLIENT_ID: $
      run: echo "GH_CLIENT_ID=\"$GH_CLIENT_ID\"" > ./local.properties
      
    - name: Run ktlintChecking
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale ktlintCheck
      
    - name: Run detekt
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale detekt

    - name: Run unit tests
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale testDebugUnitTest

    - name: Build assemble release apk
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale assembleRelease

    - name: Create android test report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}

    - name: Build assemble release apk
      run: ./android/2023-emmsale/gradlew -p android/2023-emmsale assembleRelease
